=== linh1998vn/XML/Bai 2/Orders.dtd
<!ELEMENT Orders (Order*)>
<!ELEMENT Order (OrderDate, CustomerName, Detail*)>
<!ATTLIST Order OrderNO ID  #REQUIRED>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT CustomerName (#PCDATA)>
<!ELEMENT Detail (#PCDATA)>
<!ATTLIST Detail ItemNo CDATA #REQUIRED>
<!ATTLIST Detail ItemName CDATA #REQUIRED>
<!ATTLIST Detail Quantity CDATA  "1">
<!ATTLIST Detail Price CDATA  "0">

=== linh1998vn/XML/Bai 2/Orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Orders SYSTEM "Orders.dtd">
<Orders>
    <Order>
        <OrderNO>1</OrderNO>
        <OrderDate>13/10/1998</OrderDate>
        <CustomerName>Linh</CustomerName>
        <Detail ItemNo="a" ItemName="v" Quantity="1" Price="0"></Detail>
    </Order>
    <Order>
        <OrderNO>2</OrderNO>
        <OrderDate>13/10/1998</OrderDate>
        <CustomerName>Linh</CustomerName>
        <Detail ItemNo="a" ItemName="v" Quantity="1" Price="0"></Detail>
    </Order>
    <Order>
        <OrderNO>3</OrderNO>
        <OrderDate>13/10/1998</OrderDate>
        <CustomerName>Linh</CustomerName>
        <Detail ItemNo="a" ItemName="v" Quantity="1" Price="0"></Detail>
    </Order>
    <Order>
        <OrderNO>4</OrderNO>
        <OrderDate>13/10/1998</OrderDate>
        <CustomerName>Linh</CustomerName>
        <Detail ItemNo="a" ItemName="v" Quantity="1" Price="0"></Detail>
    </Order>
    <Order>
        <OrderNO>5</OrderNO>
        <OrderDate>13/10/1998</OrderDate>
        <CustomerName>Linh</CustomerName>
        <Detail ItemNo="a" ItemName="v" Quantity="1" Price="0"></Detail>
    </Order>
</Orders>
