=== linh1998vn/XML/Bai 3/Orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
<xs:complexType name="person">
    <xs:sequence>
        <xs:element name="Name" maxOccurs="1" type="xs:string"></xs:element>
        <xs:element name="Address" maxOccurs="1" type="xs:string"></xs:element>
        <xs:element name="Email" maxOccurs="1">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\w+@\w+(\.\w+){1,3}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="item">
    <xs:sequence>
        <xs:element name="ItemNo" maxOccurs="1" type="xs:string"></xs:element>
        <xs:element name="ItemName" maxOccurs="1" type="xs:string"></xs:element>
        <xs:element name="Quantity" maxOccurs="1" default="1">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="Price" maxOccurs="1" default="0">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>

<xs:element name="Orders">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Order" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="OrderNo" maxOccurs="1" type="xs:int"></xs:element>
                        <xs:element name="OrderDate" maxOccurs="1" type="xs:date"></xs:element>
                        <xs:element name="Customer" maxOccurs="1" type="person"></xs:element>
                        <xs:element name="Detail" minOccurs="1" maxOccurs="unbounded" type="item"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== linh1998vn/XML/Bai 3/Orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<Orders
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="Orders.xsd">
    <Order>
        <OrderNo>1</OrderNo>
        <OrderDate>13/10/2022</OrderDate>
        <Customer>
            <Name>Linh</Name>
            <Address>Hà Nội</Address>
            <Email>linh1998@gmail.com</Email>
        </Customer>
        <Detail>
            <ItemNo>1</ItemNo>
            <ItemName>CPU</ItemName>
            <Quantity>30</Quantity>
            <Price>30</Price>
        </Detail>
    </Order>
    <Order>
        <OrderNo>2</OrderNo>
        <OrderDate>13/10/2022</OrderDate>
        <Customer>
            <Name>Linh</Name>
            <Address>Hà Nội</Address>
            <Email>linh1998@gmail.com</Email>
        </Customer>
        <Detail>
            <ItemNo>1</ItemNo>
            <ItemName>CPU</ItemName>
            <Quantity>30</Quantity>
            <Price>30</Price>
        </Detail>
    </Order>
    <Order>
        <OrderNo>3</OrderNo>
        <OrderDate>13/10/2022</OrderDate>
        <Customer>
            <Name>Linh</Name>
            <Address>Hà Nội</Address>
            <Email>linh1998@gmail.com</Email>
        </Customer>
        <Detail>
            <ItemNo>1</ItemNo>
            <ItemName>CPU</ItemName>
            <Quantity>30</Quantity>
            <Price>30</Price>
        </Detail>
    </Order>
    <Order>
        <OrderNo>4</OrderNo>
        <OrderDate>13/10/2022</OrderDate>
        <Customer>
            <Name>Linh</Name>
            <Address>Hà Nội</Address>
            <Email>linh1998@gmail.com</Email>
        </Customer>
        <Detail>
            <ItemNo>1</ItemNo>
            <ItemName>CPU</ItemName>
            <Quantity>30</Quantity>
            <Price>30</Price>
        </Detail>
    </Order>
    <Order>
        <OrderNo>5</OrderNo>
        <OrderDate>13/10/2022</OrderDate>
        <Customer>
            <Name>Linh</Name>
            <Address>Hà Nội</Address>
            <Email>linh1998@gmail.com</Email>
        </Customer>
        <Detail>
            <ItemNo>1</ItemNo>
            <ItemName>CPU</ItemName>
            <Quantity>30</Quantity>
            <Price>30</Price>
        </Detail>
    </Order>

</Orders>
